### ISSUE TITLE
Setup Guide?

### ISSUE THREAD

**Issue by valabil** [mwesterham/tf2-auto-profit#1]
Im intrested in this little project you are doing but im not particulary tech savy, wondering if theres any chance you could make a set up guide perhaps? Or contact me on discord steff#8991 so we could talk! Would love to hear from you

**Comment by mwesterham** [comment]
Hey valabil, I'll add a setup portion to the README when I have time. In the meantime, this project uses node.js so you would definitely need to download node.js to run the project. If you are not familiar with client-server architectures or node.js specifically here are some resources you might want to read:

https://www.geeksforgeeks.org/client-server-model/
https://www.w3schools.com/nodejs/nodejs_intro.asp
